//1. General canal can be renamed but not deleted!

//2. USERS ORDERED BY USERNAME (ALPHABETICAL)

//3. USERS TABS

//4. CONFIGURE THE CANAL MESSAGES (USERNAMES DELAY)

//5. ADD TEAM ALERT

//6. UPDATE/DELETE TEAM (BY OWNER ONLY)

//7. CAN'T DELETE ISET RADES (UPDATE NAME ONLY)

//8. LOCALIZATION : ADD EVERYTHING IN THE THREE LANGUAGES

//9. VISIT ANOTHER USER'S PROFILE